Proof Read Second Pass Chapters 1-3
MEGA65/mega65-user-guide pull request #300
Opened 2021-09-27 13:53 UTC by Impakt

Starting my 2nd pass of the user's guide. Went over Chapters 1-3. After having done a pass of the book im much more familiar with it so was able to make some changes to keep everything more consistent with capitalisation of various menus.

The main thing done in this PR was the use of keys. I made sure the tags were used, and instead of pointing out keys with `the <blah> key`, the wording is simply `<blah>`. Some parts used the former, others the latter.

I think the latter (`<blah>`) looks better so changed it all to keep the guide consistent.

2021-09-28 14:29 UTC, gurcei requested changes
Looking good, just a few comments here and there. Some might need some input from @gardners from discussions on discord.

2021-09-29 12:16 UTC, gurcei commented on settingup.tex
> +	\item A microSD Secure Digital Card (including SDHC and SDXC) can be inserted into the external microSD Card slot at the rear of the MEGA65 as a drive.
Ok, after a bit of mulling over, I'm suggesting line 88 changes to just read as:
`A microSD Card (either SDHC or SDXC) can be inserted into the external microSD Card slot at the rear of the MEGA65.`

2021-09-29 13:13 UTC, Impakt commented on appendix-basic65.tex
> +               {\bf TAB}, which advances the cursor to the next
good point i fixed it

2021-09-29 13:16 UTC, Impakt commented on appendix-decbinhex-tutorial.tex
> +a sprite's status. Now suppose we want to turn off sprite 5 and switch on
i changed the remaining ones i could find to "switch". To be turned on obviously has other meanings in this day and age and i wanted to avoid that.

2021-09-29 13:16 UTC, Impakt commented on developing-system-programs.tex
> +After that, you can simply press the reset button the side of the MEGA65i while holding \specialkey{NO SCROLL} down,
fixed

2021-09-29 13:17 UTC, Impakt commented on gettingstarted.tex
> +The Command Keys are: \specialkey{RETURN}, \specialkey{SHIFT}, \specialkey{CTRL}, \megasymbolkey + \widekey{RESTORE}.
yeah you're right, i got carried away with the find/replace

2021-09-29 13:21 UTC, Impakt commented on screen-editor.tex
> +There are a further eight colours available via \megasymbolkey. Hold \megasymbolkey and press a key from \megakey{1} to \megakey{8} to change to one of the secondary colours. The colour that is print
fixed

2021-09-29 13:36 UTC, Impakt commented on screen-editor.tex
> +You can read about all of these functions in detail in \bookvref{appendix:escapesequences}, but some are shown in this section.
I renamed the `Functions` to `Codes` as that's what they're called in the appendix. This way the titles match up with the text here .Escape Sequences was left untouched as this is what it's called in the appendix also.

2021-09-29 13:37 UTC, Impakt commented on settingup.tex
> +	\item A microSD Secure Digital Card (including SDHC and SDXC) can be inserted into the external microSD Card slot at the rear of the MEGA65 as a drive.
done

2021-09-29 22:34 UTC, gurcei commented on appendix-basic65.tex
> +               {\bf TAB}, which advances the cursor to the next
Just wanted to check if you had pushed your fix for this change, I didn't see it in the latest diffs yet.

2021-09-29 22:38 UTC, gurcei commented on appendix-decbinhex-tutorial.tex
> +a sprite's status. Now suppose we want to turn off sprite 5 and switch on
Aah, so you're ok with "turn off" staying and would prefer just to avoid the the modern "turn on" expression and use "switch on" instead, ok, got it

2021-10-01 12:38 UTC, gurcei requested changes
Looking good, just one last observation, a missing 'on' in a sentence.

2021-10-01 12:38 UTC, gurcei commented on developing-system-programs.tex
> +After that, you can simply press the reset button the side of the MEGA65 while holding \specialkey{NO SCROLL} down,
Saw a missing 'on' here:

... press the reset button **on** the side of the MEGA65...

2021-10-02 05:23 UTC, gurcei commented on gettingstarted.tex
> +Holding \megasymbolkey and pressing any key with two graphic symbols on the front prints the left-most graphic symbol to the screen.
Will leave this one be, it's true, for the most part :)

2021-10-02 05:25 UTC, gurcei commented on developing-system-programs.tex
> +After that, you can simply press the reset button the side of the MEGA65 while holding \specialkey{NO SCROLL} down,
Oh, as this is the last thing on my radar, maybe I can try make the edit via github here and then approve the merge, let's see :)

2021-10-02 05:28 UTC, gurcei approved these changes
All good ;)

2021-10-02 05:28 UTC, merged