Add a remark on how SYS maps memory when it's combined with BANK.
MEGA65/mega65-user-guide pull request #432
Opened 2021-12-04 00:48 UTC by jimnicholls

Particularly that it doesn't map the first block and addresses $0000-$1FFF is the RAM in bank 0 regardless of **BANK**.

I resisted the temptation to explain why **SYS** works this way. But I'm happy to give in to it if it's felt such an explanation would be warranted.

2021-12-11 16:13 UTC, Edilbert requested changes
This is not completely correct.
BANK value 0 to 127 refer to a complete 64K bank, ignoring the current mapping.
BANK 128 selects the current mapping.
The segment $0000 - $1FFF of BANK 0 is mapped in for BASIC, KERNAL and MONITOR mapping.
The segment $0000 - $1FFF of BANK 1 is mapped in for DOS.
Using a BANK of 0 to 127 before SYS selects the whole 64K, so SYS jumps into a mapping with 64K of pure RAM (or ROM in bank 2 or 3) - no I/O, kernal, IRQ etc. possible.
The code must then start with SEI, because ven the interrupt vectors are not accessible.

2021-12-11 22:51 UTC, SydneyUni-Jim commented
Thank for reviewing the @Edilbert.

I was trying to communciate that **BANK 4: SYS $1000** will execute the code at absolute 28-bit address $001000 and not at $041000 as I had expected.

`jmp_far` in the kernel — which **SYS** calls, via `jsr_far` — always leave bank 0 mapped in at $0000 - $1FFF, because that's where it's executing.

2021-12-11 22:59 UTC, jimnicholls commented
Thank for reviewing this @Edilbert.

I was trying to communicate that **BANK 4: SYS $1000** will execute the code at absolute 28-bit address $001000 and not at $041000 as I had expected.

`jmp_far` in the kernel — which **SYS** calls, via `jsr_far` — always leaves bank 0 mapped in at $0000 - $1FFF, because that's where it's executing and where the machine code routine needs to `RTS` to.

2021-12-11 23:06 UTC, jimnicholls commented
The existing text refers to the bank selected by **BANK** as the current bank, so I followed on with that nomenclature.

2021-12-12 08:06 UTC, Edilbert approved these changes
OK, I got the meaning now. You're right!
Because JSR_FAR is executing in the segment $000 - $1FFF of bank 0, it cannot switch that segment off, so my statement, that you get a pure 64K RAM is wrong. The lower segment is always that of bank 0, if SYS or JSR_FAR is involved. Thank you for pointing at that.

2021-12-12 08:06 UTC, merged